### ISSUE TITLE
I would like to be part of the shinx-contrib members

### ISSUE THREAD

**Issue by marcnicole** [sphinx-contrib/github-administration#1]
I wrote a small extension that create a link to a pdf file (similar to download, but open the file instaed of downloading) and as I saw that this was also requested by other users, I would like to share it under shinx-contrib.

Currently writing another extension for a project: probably too specific yet, but hope to make it more generic in the future.

Best Regards
Marc Nicole

**Comment by dhellmann** [comment]
I have sent you an invitation to join the organization as a member. I *think* after you do that you can move your existing repo into the org on your own. That's different from the instructions in the readme in this repo, so please let me know here if it works so I can update the docs. If it doesn't work, I will need for you to grant me admin rights on the repo so I can move it for you.

**Comment by marcnicole** [comment]
Hi Doug,

Thanks. It work seamlessly to join the organization.

I will do that next weekend probably.

Best Regards

Marc

Le dim. 5 janv. 2020 à 18:53, Doug Hellmann <notifications@github.com> a
écrit :

**Comment by dhellmann** [comment]
Great! I have updated the readme to reflect the fact that a member can move their own repository.

I will keep this ticket open until you've successfully imported your repository, so please let me know when that is completed (or if you run into trouble).

**Comment by stephenfin** [comment]
I'm going to assume this is resolved now. Please re-open if not. Thanks @dhellmann!
