### ISSUE TITLE
Join Org & take over maintaining sphinx-contrib/requirements

### ISSUE THREAD

**Issue by jamesbooker** [sphinx-contrib/github-administration#10]
Hello. I came across the sphinx-contrib/requirements extension and was disappointed that it wouldn't work with Sphinx v3. The original owner appears to have abandoned it in 2012 - I would like to assume ownership of it.

I have done a basic update to work in v3 (although it may not yet be best practice) and would like to submit it (see jamesbooker/requirements) as a PR.

I would then like to continue to work on it to add more functionality

Please advise. Thanks!

**Comment by dhellmann** [comment]
Step 1 is to invite you to be a member of the sphinx-contrib org. I have sent the invitation, so please comment back here when you have accepted it so I know it came through OK. (I don't get a notification, unfortunately.)

**Comment by dhellmann** [comment]
Step 2 is to ask the existing contributors if they are willing to have someone take over maintaining. 

@mforbes and @neithere, @jamesbooker would like to update sphinx-contrib/requirements for python3 and take over maintaining it. Do you have any objections to me granting admin permission on the repository to make that possible?

**Comment by jamesbooker** [comment]
> Step 1 is to invite you to be a member of the sphinx-contrib org. I have sent the invitation, so please comment back here when you have accepted it so I know it came through OK. (I don't get a notification, unfortunately.)

I have not received an invitation within GitHub - no notification, and no messages in my inbox...

**Comment by jamesbooker** [comment]
> > Step 1 is to invite you to be a member of the sphinx-contrib org. I have sent the invitation, so please comment back here when you have accepted it so I know it came through OK. (I don't get a notification, unfortunately.)
> 
> I have not received an invitation within GitHub - no notification, and no messages in my inbox...

Never mind. I found the invitation - there's no notification or inbox, it only appears on the org's main page. I have now accepted the invitation, thank you.

**Comment by jamesbooker** [comment]
Are there any objections from @mforbes or @neithere please?

**Comment by dhellmann** [comment]
I have emailed them directly, in case they aren't receiving the GitHub notifications.

**Comment by neithere** [comment]
Hey @jamesbooker, no objections from me.

Thank you for your initiative! It's a very useful project. Happy to see it getting back to life even though the previous maintainers are unable to find resources.

**Comment by dhellmann** [comment]
Thanks for the quick reply, @neithere, and for agreeing to let @jamesbooker pick up maintainership.

**Comment by dhellmann** [comment]
@jamesbooker I've added you as a maintainer on https://github.com/sphinx-contrib/requirements/

**Comment by dhellmann** [comment]
@neithere it looks like you have admin rights for producing releases on PyPI. Could you coordinate with @jamesbooker to give him access there, too, please?

**Comment by jamesbooker** [comment]
Thanks @dhellmann .

I have already emailed @neithere about the PyPi package

**Comment by dhellmann** [comment]
Excellent.

@jamesbooker, please close this ticket when everything is sorted out.

**Comment by mforbes** [comment]
No objections from my end.

**Comment by dhellmann** [comment]
Thanks, @mforbes !

**Comment by jamesbooker** [comment]
Thanks all. All sorted at PyPi, will close the issue now
