### ISSUE TITLE
Adding supporting options to FUNDING.yml

### ISSUE THREAD

**Issue by llucax** [sphinx-contrib/github-administration#11]
Hi, I'm exploring GitHub Sponsors and other sponsoring options and I was wondering if there are any policies in terms of [adding a FUNDING.yml](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) file to repositories I maintain, but that under the sphinx-contrib org.

**Comment by dhellmann** [comment]
As far as I know we haven't set a policy for sponsorship. Is there anything specific you're concerned about?

**Comment by llucax** [comment]
Not really, it's just that since the repo is part of a bigger organization I was wondering if there was any restrictions or guidelines. Basically I want to add a sponsoring button and badges to repos I maintain (first aafig, then probably mscgen). If I don't hear about anyone against it in a few days, I will move forward and close this issue.

**Comment by dhellmann** [comment]
I appreciate that you're being cautious. I don't personally have any issues with you going ahead.

**Comment by llucax** [comment]
On a different note, but I guess it doesn't make sense to open a separate issue for this, in the README of this repo it says that people having a repo in the organization should expect to be invited as a member of the organization, but I noticed I'm an outside collaborator instead of a member. Is that normal?

**Comment by dhellmann** [comment]
Sorry about that! We either missed a step in the process, or your repo was added before we formalized that process. I have sent you an invitation to join the org.

**Comment by llucax** [comment]
No worries, is not such a big deal either because I've been a bit distanced from Sphinx in the last *few* years. I was all in Bitbucket when I was more active (to give you an idea :) ). Thanks for the invite!

**Comment by llucax** [comment]
OK, since I received no oppositions, I will move forward with this and close the issue. Thanks!
