### ISSUE TITLE
inquiry | elevated roles on repositories (confluencebuilder)

### ISSUE THREAD

**Issue by jdknight** [sphinx-contrib/github-administration#12]
Recently, the [confluencebuilder](https://github.com/sphinx-contrib/confluencebuilder) repository (ported over back in the day; sphinx-contrib/confluencebuilder#183) switched from using Travis CI to GitHub actions. The transition has been working so far and there is a plan to include more actions which would require using secret keys. Inspecting the repository's settings appears to be limited:

> ![image](https://user-images.githubusercontent.com/1834509/101554460-b29c8300-3984-11eb-94e8-2bf07bd6eaa0.png)

When looking at a self-managed repository, the option is visible:

> ![image](https://user-images.githubusercontent.com/1834509/101554515-ca740700-3984-11eb-9a65-6baadc6e32dc.png)

I suspect this is a result of [not being assigned an `admin` role on the repository](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository). While I can understand the desire to not be giving out administrator assignments at the organization level, is there a way that individual repositories can be given a more elevated role to allow access to these options? I'm not too familiar with permission schemas/role assignments in GitHub, so I am not sure what the best approach is.

**Comment by stephenfin** [comment]
No issues with adding admin role for individual projects fwict. I've moved you to `admin` role. Let me know if you need any other repo updated
