### ISSUE TITLE
Resurrecting ansi plugin

### ISSUE THREAD

**Issue by ssbarnea** [sphinx-contrib/github-administration#13]
I would like to request ownership of https://github.com/sphinx-contrib/ansi alongside @jenisys in order to to revive this plugin.

The scope is to bring this back to life and make it compatible with current versions of sphinx. I do have enough experience maintaining python packages and setting up CI pipelines for them.

If I could receive an invite it would be great. I see that @webknjaz is already a member and I guess he could vet for me.

**Comment by webknjaz** [comment]
@dhellmann I confirm that Sorin is trustworthy and is totally able to resurrect the project given. I worked with him on various repos in Ansible ecosystem.

**Comment by dhellmann** [comment]
Let's see if we can get any of the existing contributors to confirm that it's OK to transfer maintainership.

I see @mforbes had the most recent commit, although most of the others were from @lunaryorn, who is listed as the author on PyPI.

@leeping is listed as the maintainer on PyPI. If you're going to produce releases, you'll need access to the project there, too.

@stephenfin has commit access. Stephen, did you import the repo into the sphinx-contrib org?

**Comment by leeping** [comment]
@ssbarnea Hi there, I'd be happy to give you access to the PyPI project.  I only made the PyPI project because no one else had, and I wanted to make my colored HTML output available on readthedocs.

**Comment by ssbarnea** [comment]
FYI, my pypi username is the same as github: ssbarnea

**Comment by leeping** [comment]
Great, I've now invited you to be an owner of the project on PyPI.

**Comment by lunaryorn** [comment]
Hey I've honestly got no idea what this was, so feel free to do with it whatever you want within the limits of its licence.

Cheers

**Comment by dhellmann** [comment]
> Great, I've now invited you to be an owner of the project on PyPI.

Thanks, @leeping!

**Comment by dhellmann** [comment]
> Hey I've honestly got no idea what this was, so feel free to do with it whatever you want within the limits of its licence.
> 
> Cheers

Thanks, @lunaryorn.

@ssbarnea I have invited you to be a maintainer on the `ansi` repo. When you've accepted that invitation, you should have permission to invite other contributors and approve pull requests.

I think that means we can close this ticket, but please reopen it if I've missed something or you need other assistance.

**Comment by ssbarnea** [comment]
@dhellmann Thanks. I accepted both pypa and github invites. You will still need to boost my privledges on github because current ones do not allow me to perform various needed tasks, documented at https://github.com/sphinx-contrib/ansi/issues/6 (configuring secrets, branch access, webhooks).

**Comment by dhellmann** [comment]
@ssbarnea I've changed you from Maintainer to Admin, so you should have permission to do anything now. I also sent you an invitation to join the sphinx-contrib org, since I noticed you weren't a member. That's not required, but it lets you control some personal settings like notifications so might be of use.

**Comment by ssbarnea** [comment]
Thanks you and only good wishes for 2021!
