### ISSUE TITLE
Maintenance of the doxylink extension

### ISSUE THREAD

**Issue by JasperCraeghs** [sphinx-contrib/github-administration#14]
My colleagues and I want to contribute to [sphinxcontrib-doxylink](https://github.com/sphinx-contrib/doxylink), but the owner of this repository seems inactive. I've emailed him, but he hasn't replied. 

Please give me the permissions I need to merge pull requests and make a release. I am willing to take over maintenance of this repository. You can find my contribution in [this PR](https://github.com/sphinx-contrib/doxylink/pull/27).

**Comment by dhellmann** [comment]
@milliams is the repo admin. Is that who you contacted?

**Comment by JasperCraeghs** [comment]
Yes, he is the person I tried to contact.

**Comment by dhellmann** [comment]
OK, this time of year it's common for folks to go offline for extended periods of time. Let's give @milliams a few more days to respond. If I haven't heard back by 8 Jan then I'll go ahead and give you access.

**Comment by JasperCraeghs** [comment]
He has been away from his computer. He has given me permission today.
