### ISSUE TITLE
Travis CI builds not triggering

### ISSUE THREAD

**Issue by jonascj** [sphinx-contrib/github-administration#15]
Anyone else seeing Travis CI builds not triggering for their sphinx-contrib/ projects?

sphinx-contrib/images (https://travis-ci.com/github/sphinx-contrib/images/builds) builds are not triggering and if I sign in to Travis CI with my github account (oauth) it shows the the following error:

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

![scrot_2021-01-10_231901_1899x369](https://user-images.githubusercontent.com/3301843/104137124-e65f3400-539a-11eb-9dc9-8d4f7a911de4.png)

**Comment by jonascj** [comment]
I contacted Travis CI support, asking them why builds were not triggering and/or why I saw the above mentioned (error)message.

This is their first reply. Maybe some policy has changed in the past 4-6 months and now a project like this needs to apply for open source build minutes, or maybe this projects has just finally run out of build minutes. They didn't answer why I saw this message now.

> 
> Thanks for contacting Travis-CI Support! We would love to help.
> 
> We offer an Open Source Subscription for free to non-commercial open-source projects. To qualify for an Open Source subscription, the project must meet the following requirements:
> 
>     You are a project lead or regular committer (latest commit in the last month)
>     Project must be at least 3 months old and is in active development (with regular commits and activity)
>     Project meets the OSD specification
>     Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)
>     Project can not provide commercial services or distribute paid versions of the software
> 
> 
> Does this sound like you and your project? We'd be very happy to support you!
> 
> However, if your project does not match these requirements or you have further questions [1], please feel free to ask!
> 
> We look forward to your response if you meet these requirements to proceed with the next steps.
> 
> Thank you

**Comment by dhellmann** [comment]
I've been moving my projects to use GitHub actions for CI. See https://github.com/sphinx-contrib/spelling/pull/111 and some other recent closed PRs on that repo for examples.

**Comment by jonascj** [comment]
@dhellmann Cheers, I found your mentioning of Travis changing OSS plans: https://github.com/sphinx-contrib/spelling/issues/107

I'll have to look into that then.
