### ISSUE TITLE
Can I take over sphinxcontrib-lilypond?

### ISSUE THREAD

**Issue by SilverRainZ** [sphinx-contrib/github-administration#16]
Hi all, This extension is no longer works due to lack of maintaince.
I wanna to apply for maintainer of this repo. In fact I wrote https://sphinx-notes.github.io/lilypond/ , It is no compatible with the current repo, can I directly replace it? I think no one is using this extension -- for it is broken.

**Comment by stephenfin** [comment]
It looks like https://github.com/sphinx-contrib/lilypond isn't actually what's published on PyPI. Instead, it seems like the source for [the PyPI package](https://pypi.org/project/sphinxcontrib-lilypond/) is https://github.com/FabriceSalvaire/sphinx-lilypond. You should probably contact @FabriceSalvaire and see if they'd like to add you to the project and/or move that project here (we can delete https://github.com/sphinx-contrib/lilypond so they can migrate it)

**Comment by stephenfin** [comment]
Closing. I don't think there's anything more we can do here.
