### ISSUE TITLE
I'd love to join

### ISSUE THREAD

**Issue by Lennonka** [sphinx-contrib/github-administration#17]
Hi there!

I'd love to join sphinx-contrib. I've been a user and passionate fan of Sphinx for several years and I'm currently considering rewriting docx builder for the newest version of Sphinx because I could use it in my freelance work as a technical writer.

Thanks!

**Comment by stephenfin** [comment]
Hi, if you've a repository ready to go, please point to it and we can help you transfer it if that would be useful

**Comment by Lennonka** [comment]
Hi Stephen. I don't have one yet, it would be great if I could get one in your organisation right away. I'm basing the code on the outdated extension, but it seems I'll have to rewrite it greatly.

**Comment by dhellmann** [comment]
We usually want to import an existing repository. That gives you a chance to set it up the way you like, add code, etc. and then all of those settings are transferred when the repository is moved. It also means we don't end up creating repositories that stay empty.

So, please do go ahead and start working on the new extension and we can help you bring it into the org when you're ready.

**Comment by Lennonka** [comment]
Sure, thanks for the info!
