### ISSUE TITLE
Adding `sphinxcontrib-svgbob` to the organisation

### ISSUE THREAD

**Issue by althonos** [sphinx-contrib/github-administration#18]
Hi !

I made [althonos/sphinxcontrib-svgbob](https://github.com/althonos/sphinxcontrib-svgbob), so I'd like to join the organisation if possible :smile: 

It's a Sphinx extension to render ASCII diagrams as SVG using Svgbob. It embeds its dependencies statically so it's suitable to use on [readthedocs.org](https://readthedocs.org). In case the builder does not support SVG images, it will render the diagram in a code block instead to preserve the formatting.

**Comment by stephenfin** [comment]
@althonos I'm invited you as a member of the organization. Please accept this, which should allow you to move the project. When you move it, please drop the `sphinxcontrib-` prefix since this is unnecessary given the org name. Thanks!

**Comment by althonos** [comment]
Hi @stephenfin thanks! I moved the repository but it doesn't seem like i'm able to change its name (or access the settings page for that matter) for now, maybe it's because I just joined or maybe i just don't have the proper rights to do so!

**Comment by stephenfin** [comment]
Spot on. I renamed it for you and added you as an admin to the repo so you can do that yourself in the future. Let me know if you've any further issues!

**Comment by althonos** [comment]
Perfect, thank you!
