### ISSUE TITLE
AutoDoc Airflow DAGs

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [sphinx-contrib/github-administration#19]
I'd like to join the org, I've created an extension that documents [Airflow DAGs](https://github.com/ConstantinoSchillebeeckx/airflow_auto_doc).

**Comment by dhellmann** [comment]
Hi! I have sent an invitation for you to join the org. Please close this issue when you have accepted the invitation. Let us know if you need any help moving your repo over, too.
