### ISSUE TITLE
zopeext maintainer.

### ISSUE THREAD

**Issue by mforbes** [sphinx-contrib/github-administration#2]
Please make me a collaborator for [zopeext](https://github.com/sphinx-contrib/zopeext) as I am the maintainer and would like to upload new versions.

**Comment by dhellmann** [comment]
I see an old invitation to make you an administrator. I will remove that and create a new one, which should trigger an email to you to accept.

**Comment by stephenfin** [comment]
Looks like you have access now, @mforbes. Please let us know if there is anything else you need
