### ISSUE TITLE
sphinx-contrib/googleanalytics unmaintained

### ISSUE THREAD

**Issue by thclark** [sphinx-contrib/github-administration#20]
Hi,

Can I be added as a member to help maintain googleanalytics please?

There are some [PRs standing open for years](https://github.com/sphinx-contrib/googleanalytics/pulls) and I can merge them to resurrect it.

Thanks,

Tom

**Comment by domenkozar** [comment]
I completely forgot I wrote this package 11 years ago so I thought the request is for me to pick it up :))

**Comment by thclark** [comment]
OK @stephenfin I've heard back from Domen and he's added me as an owner on the pypi project. Could you add me as a maintainer here please?

Also; how does it work re. testing and integrations - do you have a standardised pattern for github actions etc?

**Comment by stephenfin** [comment]
I dropped the ball here. Are you still interested in this, @thclark / @jelmer

**Comment by jelmer** [comment]
> I dropped the ball here. Are you still interested in this, @thclark / @jelmer ?

Yup

**Comment by stephenfin** [comment]
> Also; how does it work re. testing and integrations - do you have a standardised pattern for github actions etc?

Nothing mandated here. I think everyone does their own thing. I'd advise looking around, finding a project you like and copying that. I have decent tests (IMO) for https://github.com/click-contrib/sphinx-click that might be of use as a blueprint.

**Comment by thclark** [comment]
Hi @stephenfin thanks for picking this up, but for me I've picked up a whole bunch of projects to maintain since, so no longer have capacity. Good luck with the project though, I still think it's valuable :)

**Comment by thclark** [comment]
I do have ownership on the pypi project, so can organise transfer or extra access to anyone wanting to take up on this? Should that be you @stephenfin or @jelmer, or both?

**Comment by jelmer** [comment]
Extra access would be great (rather than having a single person as owner). I'm "jelmer" on pypi

**Comment by stephenfin** [comment]
You can add `jelmer` and `sphinx-contrib` on PyPI

**Comment by thclark** [comment]
Invited you both. I've also accepted the invitation to collaborate here on GitHub; even though I've no bandwidth right now, at some point I might, so that would save some admin at that point.
