### ISSUE TITLE
New extension for prefect flow visualizations 

### ISSUE THREAD

**Issue by sp1thas** [sphinx-contrib/github-administration#21]
Hello everyone,

I'm implementing this [sphinx extension](https://github.com/sp1thas/prefectviz) for [prefect](https://github.com/prefecthq/prefect) users in order to add [flow visualizations](https://docs.prefect.io/core/advanced_tutorials/visualization.html) into sphinx documentation. I'm planning to add more prefect-focused directives and rename it to something more generic like `sphinx-contrib/prefect`.

 I would like to join the org in order to move the repo :)

Cheers.

**Comment by dhellmann** [comment]
Hi, @sp1thas, I've sent you an invitation to join the org. I don't receive a notification when you accept, so please close this ticket when you've successfully joined.

Welcome!
