### ISSUE TITLE
request for 2 new repositories

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/github-administration#23]
Hi there i'm new to sphinx and I was missing 2 things when I started: 
- the ability to write down inline icons (in both html and latex output) 
- the ability to add icon in the `guilabel` role (in both html and latex output)

I have created 2 extentions for that purpose: 
- https://github.com/12rambau/sphinx-icon
- https://github.com/12rambau/sphinx-btn

I think they would be better if they live here instead of in my personal repos. 
I've already prepared the repository to mimick other libs that live here (my extention lives in the "sphinxcontrib" namespace)

**Comment by stephenfin** [comment]
I've sent you an invitation to the organization, which should allow you to transfer your project to the organization. Please let us know if you've any issues.

**Comment by 12rambau** [comment]
thanks I've migrated the 2 repositories: 
- https://github.com/sphinx-contrib/sphinx-icon
- https://github.com/sphinx-contrib/sphinx-btn

But I lost the administration settings in the process, preventing me to change the secrets (for Pypi release) and the name. Could you set me back as administrator of these 2 repos ?

**Comment by stephenfin** [comment]
Done for both. We really must figure out a way to make that the default role for transferred repos.

I'm going to close this now since it seems you're sorted. Let us know if not!
