### ISSUE TITLE
Can I have sphinx-contrib/sphinx-lint?

### ISSUE THREAD

**Issue by JulienPalard** [sphinx-contrib/github-administration#24]
cf. https://github.com/sphinx-doc/sphinx/issues/10143

**Comment by stephenfin** [comment]
I've invited you to the organization. This will let you create a new repo or transfer an existing one. Let me know if you have any issues.

**Comment by JulienPalard** [comment]
https://github.com/sphinx-contrib/sphinx-lint transferred, thanks!

Two questions:
- [The doc](https://github.com/sphinx-contrib/github-administration#how-do-i-add-a-new-repo-to-sphinx-contrib) tells I should remove the `sphinx-` prefix, is it mandatory? Feels like `sphinx-lint` is better than `lint`.
- Can I get the rights to manage the commiters on this repo? Looks like I lost most rights during the migration.

**Comment by stephenfin** [comment]
> Two questions:
> 
>     * [The doc](https://github.com/sphinx-contrib/github-administration#how-do-i-add-a-new-repo-to-sphinx-contrib) tells I should remove the `sphinx-` prefix, is it mandatory? Feels like `sphinx-lint` is better than `lint`.

Yeah, it probably makes more sense as-is.

>     * Can I get the rights to manage the commiters on this repo? Looks like I lost most rights during the migration.

Done
