### ISSUE TITLE
permissions on sphinx-contrib/youtube

### ISSUE THREAD

**Issue by dham** [sphinx-contrib/github-administration#25]
I am the maintainer of sphinx-contrib/youtube. I am trying to set up readthedocs documentation hosting for the extension. It appears I don't have the required permissions to set up webhooks on the repository. Can I please be granted those permissions.

**Comment by dhellmann** [comment]
Sorry about that, @dham! When the repo was imported you were retained as a "writer" but not "administrator." I've fixed that now. Give it another try, and if you have everything you need please close this ticket. If you need an org administrator to take some action, we can track that here.
