### ISSUE TITLE
Please enable issue tracker  in sphinxcontrib-qthelp

### ISSUE THREAD

**Issue by kloczek** [sphinx-contrib/github-administration#26]
It would be rerally nice to enable issue tracker on https://github.com/sphinx-doc/sphinxcontrib-qthelp/

**Comment by stephenfin** [comment]
That's a project in the github.com/sphinx-doc organization. This is github.com/sphinx-contrib.

**Comment by stephenfin** [comment]
To be clear, you'll need an admin in the sphinx-doc organization to do that. I'm only a lowly maintainer there.

**Comment by AA-Turner** [comment]
Sorry for the noise, I misled @kloczek by suggesting opening an issue here.

A

**Comment by stephenfin** [comment]
All good!

**Comment by AA-Turner** [comment]
Maintainership isn't lowly! There are three admins in @sphinx-doc (@stephenfin I think you're able to see the list as well), hopefully one is able to comment on the original issue. We should move the converstation back there.

A
