### ISSUE TITLE
no more maintainer on sphinxcontrib/images

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/github-administration#27]
I started to use sphinxcontrib/images for my documentations some time ago. I offered a single PR so far to change the pointer but I think that @jonascj is not using github any more and he's looking for a 2nd maintainer (as mentioned in https://github.com/sphinx-contrib/images/issues/20). I would like to participate more in this repository but i don't manage to contact him. Does anyone know where he can be contacted ?

**Comment by jonascj** [comment]
Hi @12rambau . Thank you for sticking to it and trying to get your PR merged into the official repo/packaged. Maye you should be that new or second maintainer? I'll head over to the repo now and hopefully we can pick up where we left off. And sorry if I've missed direct attempts to get things moving - I must have overlooked or misconfigured e-mail notifications (and of course had my focus elsewhere).

**Comment by dhellmann** [comment]
Hi, @12rambau and @jonascj, it sounds like you're all set but let me know if you need any help with admin changes or anything like that.

**Comment by 12rambau** [comment]
> And sorry if I've missed direct attempts to get things moving - I must have overlooked or misconfigured e-mail notifications (and of course had my focus elsewhere).

I fully understand that it's not your priority or that you don't have enough time to dedicate to OSS. I still have so I would be glad to help. Let's see what we can do from the repo.

**Comment by stephenfin** [comment]
@12rambau @jonascj Did you get this sorted? I'm going to assume so and close this issue. Please reopen if there is still something outstanding that we need to help with.

**Comment by 12rambau** [comment]
yes we did sorry for not closing it
