### ISSUE TITLE
Install codecov for `sphinxcontrib-towncrier`

### ISSUE THREAD

**Issue by webknjaz** [sphinx-contrib/github-administration#28]
Hi @dhellmann, could you enable https://github.com/apps/codecov for the $sbj repo? Installing for the whole org would also work, if desired. But just this repo is enough for me.

**Comment by dhellmann** [comment]
I've enabled it on sphinxcontrib-towncrier. Please give it a try and close this ticket if everything is working as expected.

**Comment by stephenfin** [comment]
I assume things worked as expected
