### ISSUE TITLE
permissions on sphinx-contrib/imageembed

### ISSUE THREAD

**Issue by jschueller** [sphinx-contrib/github-administration#29]
hi, @JanGutter the maintainer of https://github.com/sphinx-contrib/imageembed claims he no longer has permissions on the repository

could it be possible to re-add him (and/or me eventually) so new PRs can be merged ?

**Comment by dhellmann** [comment]
I see the user @bollie has admin privileges on that repo. The commits in the repo come from @JanGutter and you referenced @JanGutter in this ticket. Both users seem to have the same name. Are they the same person with 2 accounts or was there a mixup when the repo was moved to this org?

**Comment by jschueller** [comment]
Its probably the same person: same avatar, both accounts link to the same personal page

**Comment by bollie** [comment]
Hi, apologies yeah, I should own both accounts. I thought I
transferred everything from @bollie to @JanGutter, but I obviously forgot
about this. Let me try logging in to my old account again.

**Comment by stephenfin** [comment]
I assume you got sorted. Please reopen this if there is still an issue.
