### ISSUE TITLE
Moving sphinxcontrib-prettyspecialmethods to sphinx-contrib

### ISSUE THREAD

**Issue by eric-wieser** [sphinx-contrib/github-administration#3]
I'd like to join the org so that I can migrate @Thom1729's https://github.com/eric-wieser/sphinxcontrib-prettyspecialmethods here

**Comment by dhellmann** [comment]
Invitation sent.

**Comment by eric-wieser** [comment]
Moved the repo. Can I have permissions to rename it?

**Comment by stephenfin** [comment]
You should have maintainer privileges now

**Comment by eric-wieser** [comment]
I don't seem to have permission to rename the repo.

**Comment by dhellmann** [comment]
I've changed you to `admin` on the repo so you should be able to now.

**Comment by eric-wieser** [comment]
Thanks, that did the trick. @Thom1729, if you want to maintain this, please comment here asking to be added to the organization.
