### ISSUE TITLE
Help maintaining openapi plugin

### ISSUE THREAD

**Issue by fcollonval** [sphinx-contrib/github-administration#30]
Dear admin,

I would like to help with the maintenance of https://github.com/sphinx-contrib/openapi in particular because its dependency stack has not been updated in ages. In particular the underlying m2r dependency.

**Comment by stephenfin** [comment]
Have you reached out to the maintainer(s) of that contribution directly? That should be your first port of call. There's a good chance they'd be happy to work with you if you ask. We can't do anything unless the extension is clearly unmaintained and you've tried multiple avenues to get in contact with the maintainer(s).

**Comment by fcollonval** [comment]
@stephenfin thanks for the reply. I'll contact the maintainers.
