### ISSUE TITLE
Request to add my `repl` extension to the org

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [sphinx-contrib/github-administration#31]
Hi, I've developed an extension to run the python interpreter concurrently to auto-form doctest-style blocks from Python codes. Basically, doctest extension without test answers. I don't think this has been done by anyone yet, and I'd like to publish this extension as a part of sphinx-contrib.

https://github.com/tikuma-lsuhsc/sphinxcontrib-repl

Thanks

**Comment by dhellmann** [comment]
Welcome!

I've sent you an invitation to join the org. After you accept it, you should be able to move the repo in yourself. If you have problems, let me know here and I'll try to help. When you're done with the move we can close this ticket.

**Comment by tikuma-lsuhsc** [comment]
@dhellmann - thanks. I'll move the repo tonight and will let you know when done. Is there any guideline to publishing it on pip? (Particular package name, etc.)

**Comment by dhellmann** [comment]
We don't have any hard rules, but I think most of the packages are named something like "sphinxcontrib-repl" so following that pattern on pip would be good.

**Comment by tikuma-lsuhsc** [comment]
Got the repo moved to https://github.com/sphinx-contrib/repl Thanks.

**Comment by tikuma-lsuhsc** [comment]
I accidentally took myself off the repo (I wasn't thinking a whole lot...) Is there someway to restore my access from org administrator? Thanks.

https://github.com/sphinx-contrib/repl

**Comment by tikuma-lsuhsc** [comment]
@dhellmann - thank you!!
