### ISSUE TITLE
New extension

### ISSUE THREAD

**Issue by Freed-Wu** [sphinx-contrib/github-administration#35]
Hi, I want to import [a new extension](https://github.com/Freed-Wu/sphinxcontrib-eval). TIA!

**Comment by dhellmann** [comment]
Welcome!

I have invited you to join the sphinx-contrib org. After you accept the invitation, you should be able to move your repository into the org. You can use this issue to let me know if you have any trouble. Please close the issue when the transfer is complete.

**Comment by Freed-Wu** [comment]
![screen-2023-01-15-00-40-02](https://user-images.githubusercontent.com/32936898/212483983-ae0ef35b-b357-4983-ad82-7cc43ce6df70.jpg)

How can I enable [pre-commit.ci](https://pre-commit.ci/) and [codecov](https://codecov.io)?

**Comment by dhellmann** [comment]
I've changed your role on the repo to admin. That should give you the permissions you need to enable those tools.
