### ISSUE TITLE
Add owner/contributor rights to https://github.com/sphinx-contrib/exceltable

### ISSUE THREAD

**Issue by juhamust** [sphinx-contrib/github-administration#40]
Hi. I'm the original author of the https://github.com/sphinx-contrib/exceltable extension 👋 Please give me adjust permission & organization rights accordingly:

- Owner: https://github.com/juhamust
- Collaborator: https://github.com/Saptak625

Thanks!

**Comment by dhellmann** [comment]
Hi, @juhamust. I have sent you an invitation to join the sphinx-contrib org. After you accept that, let me know here and I will set you up as owner of the repo.

**Comment by juhamust** [comment]
Thank you for the invite, @dhellmann. I've now accepted it and you can mark me as a repo owner 👍

**Comment by dhellmann** [comment]
@juhamust Welcome! :-)

You are now a maintainer of the repo. I'll leave it up to you to invite other contributors and set the permissions they need. Let me know if any of them need to be invited to the org.

I'll close this ticket, but let me know if I can do anything else to help.
