### ISSUE TITLE
I'd like to join

### ISSUE THREAD

**Issue by benediktmag** [sphinx-contrib/github-administration#41]
I'd like to join sphinx-contrib. 

I have been using sphinx bundled with homemade settings and extensions for teaching material (mostly in university mathematics), see http://edbook.hi.is

The first extensions I would like to add to sphinx-contrib is for embedding GeoGebra applets:
https://github.com/edbook/sphinxcontrib-geogebra

Best,
Benedikt

**Comment by dhellmann** [comment]
Hi, @benediktmag , I have invited you to join the GitHub org. I will not see a notification when you accept, so please close this ticket if you are able to successfully join or leave a comment here to let me know if you have an issue.

Welcome!
