### ISSUE TITLE
Include vimbuilder

### ISSUE THREAD

**Issue by girishji** [sphinx-contrib/github-administration#49]
I request the following extension be included (if appropriate). It creates Vim help files from rst files. See the link at the end of readme file below.

https://github.com/girishji/vimbuilder

**Comment by dhellmann** [comment]
Hi, @girishji , I have sent you an invitation to join the `sphinx-contrib` organization. After you accept that invitation, you should have all of the permissions you need to move the repository into the org. If you let me know when that is done, I will make sure you have admin privileges on the repo after the move (sometimes permissions are changed in the transfer).

Post here to let me know if you run into any trouble. We can hold this ticket open until the new repo is completely set up.

**Comment by girishji** [comment]
@dhellmann thank you, I have transferred the repository.
