### ISSUE TITLE
Becoming member

### ISSUE THREAD

**Issue by MikeSmithEU** [sphinx-contrib/github-administration#5]
Hi,

I would like to become a member so I can add a small extension that provides a directive for inline Graphviz graphs via gravizo.

Initial version is available at https://github.com/MikeSmithEU/sphinxcontrib-gravizo

**Comment by dhellmann** [comment]
I have sent an invitation

**Comment by MikeSmithEU** [comment]
Thanks! The project has been moved to sphinx-contrib, version bumped and re-published on pypi.

Is there a generic sphinx-contrib user to add as a maintainer or owner to pypi?

https://github.com/sphinx-contrib/gravizo
https://pypi.org/project/sphinxcontrib-gravizo/

**Comment by MikeSmithEU** [comment]
Thanks! The project has been moved to sphinx-contrib, version bumped and re-published on pypi.

Is there a generic sphinx-contrib user to add as a maintainer or owner to pypi?

https://github.com/sphinx-contrib/gravizo
https://pypi.org/project/sphinxcontrib-gravizo/

**Comment by stephenfin** [comment]
Sure. You can use [sphinx-contrib](https://pypi.org/user/sphinx-contrib/). I don't think we've cut any releases for any projects from that yet, but the idea is that we would be able to eventually.
