### ISSUE TITLE
Library add request: sphinxcontrib-typer

### ISSUE THREAD

**Issue by bckohan** [sphinx-contrib/github-administration#51]
Hey folks,

I'm requesting to add [sphinxcontrib-typer](https://github.com/bckohan/sphinxcontrib-typer). It autodocs typer and click commands to svg, html or text using the console formatting supplied by typer and rich.

- [PyPi](https://pypi.org/project/sphinxcontrib-typer/)
- [docs](https://sphinxcontrib-typer.readthedocs.io/)
- build: poetry
- formatting: black
- testing: pytest - coverage ~85%

Please let me know if I need to do anything else!

Example:

```python

import typer
import typing as t

app = typer.Typer(add_completion=False)

@app.callback()
def callback(
    flag1: bool = typer.Option(False, help="Flag 1."),
    flag2: bool = typer.Option(False, help="Flag 2.")
):
    """This is the callback function."""
    pass


@app.command()
def foo(
    name: str = typer.Option(..., help="The name of the item to foo.")
):
    """This is the foo command."""
    pass


@app.command()
def bar(
    names: t.List[str] = typer.Option(..., help="The names of the items to bar."),
):
    """This is the bar command."""
    pass


if __name__ == "__main__":
    app()
```

```rst
.. typer:: examples.example:app
    :width: 100
```

![example](https://github.com/sphinx-contrib/github-administration/assets/26320749/94caea5c-3b9c-4a6a-9a97-20d6b11b1395)

**Comment by dhellmann** [comment]
Hi, @bckohan ,

I have sent you an invitation to join the GitHub org. After you accept that, you should be able to move the repo yourself (please review the naming convention suggestions at the end of the readme https://github.com/sphinx-contrib/github-administration). 

After the move, you may need me to re-grant you admin permission on the repo. If that's the case, comment here on this ticket and let me know.

When we're all done, and you have the permissions you need, we can close this ticket.

Welcome, and thank you for contributing!

**Comment by bckohan** [comment]
Thanks @dhellmann,

I've transferred the repository to here: https://github.com/sphinx-contrib/typer and issued a new release with updated meta data. Everything looks good - **I do need admin rights granted**.

Thanks!
Brian

**Comment by dhellmann** [comment]
I've updated the repo to give you admin permissions. Let me know if you need anything else, otherwise go ahead and close the ticket out.

**Comment by bckohan** [comment]
Great thankyou Doug!
