### ISSUE TITLE
add me as administrator of sphinxcontrib-copier

### ISSUE THREAD

**Issue by 12rambau** [sphinx-contrib/github-administration#53]
I recently created a [`copier-sphinxcontrib`](https://github.com/sphinx-contrib/copier-sphinxcontrib) template to replace the cookiecutter one. 

The biggest advantage (along with a small refresh of everything) will be the capacity for a templated repository to be updated when something changes within the `copier-sphinxcontrib` repository. It's exactly what copier has been designed for and it works super nicely with my Python package template that I used as a source. 

Now I would like to detach the said repository from my [`pypackage`](https://github.com/12rambau/pypackage) repository to make changes dedicated to sphinx-contrib. To do so I want to follow the GitHub instructions from this [page]( https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork#detaching-a-fork)

Nothing fancy but I need to delete the repository first to recreate it from my local git (without the fork link). I don't have sufficient rights to delete the repo, would someone from the development team increase my rights? 

Don't delete it yourself as I will do the said modifications anyway.

**Comment by dhellmann** [comment]
That process page looks like it's really just walking you through the steps of making a repo with the same content without forking using the GitHub UI so the repositories aren't linked in their database. There are a few different ways to set up the new repo before an org admin deletes the old one. If you want to do it that way, I can help with making a new repo and giving you admin rights.

**Comment by 12rambau** [comment]
hmmm you are right I remember in the past doing by sending an email to the github support and they were simply unlinking the 2 repositories. Also I made a first release (GitHub release) that would be lost if I follow the process presented in the page i shared. Let me try to find back the old process and I'll close this issue.

**Comment by 12rambau** [comment]
ok the "good aold way" is still available, it's simply hidden behind the new github support bot. It's done, copier-sphinxcontrib is now the root of its own network. 

Closing the issue as I don't need any aditional rights.
