### ISSUE TITLE
jinja-autodoc

### ISSUE THREAD

**Issue by azmeuk** [sphinx-contrib/github-administration#62]
Hi,

I would like to move my project jinja-autodoc into sphinx-contrib:
https://jinja-autodoc.readthedocs.io/en/latest/
https://github.com/yaal-coop/jinja-autodoc

This is a fork/rewrite of the long unmaintained [sphinxcontrib.jinjadomain](https://github.com/offlinehacker/sphinxcontrib.jinjadomain) for which I could not have response from the maintainer.

**Comment by stephenfin** [comment]
Hi @azmeuk,

I have sent you all an invitation to join the GitHub org. After you accept that, you should be able to move the repo yourself (please review the naming convention suggestions at the end of the readme https://github.com/sphinx-contrib/github-administration).

After the move, you may need me to re-grant you admin permission on the repo. If that's the case, comment here on this ticket and let me know.

When we're all done, and you have the permissions you need, we can close this ticket.

Welcome, and thank you for contributing!

**Comment by azmeuk** [comment]
I transferred the project, but indeed I lost some permissions in the process.
About the naming convention, is `jinja-autodoc` OK?
I invited sphinx-contrib on pypi and testpypi.

**Comment by stephenfin** [comment]
> I transferred the project, but indeed I lost some permissions in the process.

That should be addressed now.

> About the naming convention, is `jinja-autodoc` OK?

Yes, that's a-okay.

> -I invited sphinx-contrib on pypi and testpypi.

Great, thank you!

**Comment by stephenfin** [comment]
I'm going to close this now that the transfer is complete and permissions issues should have been resolved. If you still have any issues, please feel free to re-open.

**Comment by azmeuk** [comment]
@stephenfin It looks like the invitation on the Pypi repos has expired. I just sent you a new one.
