### ISSUE TITLE
Abandoned 'email' extension

### ISSUE THREAD

**Issue by lcnittl** [sphinx-contrib/github-administration#7]
It seems that the [email extension](https://github.com/sphinx-contrib/email) is without maintainers ([This is what makes me think that there are no active maintainers](https://github.com/sphinx-contrib/email/pull/1#issuecomment-615176868)), please correct me if I am wrong. There are open PRs, crucial for python3 support.

If it is okay, I would like to maintain this extension to make it fit for the present.

If this is not okay, would there be someone that checks and accepts the PR(s)?

In any case, thanks.

**Comment by dhellmann** [comment]
Let's see what @s0undt3ch wants to do before we proceed.

**Comment by s0undt3ch** [comment]
I have no objection to having someone else maintain the extension.

**Comment by dhellmann** [comment]
Ok, thanks. 

Would anyone like to volunteer?

**Comment by lcnittl** [comment]
I would, unless you want someone that is already member of sphinx-contrib.

**Comment by s0undt3ch** [comment]
Also, to anyone continuing the work on the extension, Thank You.

**Comment by dhellmann** [comment]
Thank you, @s0undt3ch, for creating the project and helping with a smooth hand-off.

@lcnittl I have sent you an invitation to join the sphinx-contrib org. After you accept that, please comment back here to let me know and then I will give you permissions on the repository.

**Comment by lcnittl** [comment]
Thanks @s0undt3ch! Last thing missing might be to alter the [pypi](https://pypi.org/project/sphinxcontrib-email/) maintainer. Would you mind adding me ([`lcnittl`](https://pypi.org/user/lcnittl/)) as maintainer? I will then also add [`sphinx-contrib`](https://pypi.org/user/sphinx-contrib/). Thank you!

Thank you @dhellmann, invite was accepted.

**Comment by dhellmann** [comment]
@lcnittl I have added you as an admin for https://github.com/sphinx-contrib/email, which should let you add other contributors in the future. Let me know if there's anything else you need for me to do.

**Comment by s0undt3ch** [comment]
Owner PyPi invitation sent.
Thank You for taking over the project

**Comment by lcnittl** [comment]
@dhellmann Great, thank you!

@s0undt3ch Thanks for sending the invite, I have just now accepted it. Thank you for starting the project and handing it over so smoothly.

With all these things done, I am closing this issue. Cheers!
