### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by hason** [sphinx-contrib/github-administration#8]
I would like to become a member so I can add an extension that provides a directive for diagrams via https://kroki.io https://github.com/hason/sphinx-kroki

Best Regards
Martin Hasoň

**Comment by dhellmann** [comment]
@hason I have sent you an invitation.

Please use this issue to let me know if you have problems migrating the repository, and we can close it when the migration is done.

**Comment by hason** [comment]
@dhellmann I would like to rename the repository (https://github.com/sphinx-contrib/sphinx-kroki to https://github.com/sphinx-contrib/kroki), but unfortunately I do not have the rights.

**Comment by stephenfin** [comment]
Done!

**Comment by dhellmann** [comment]
Thanks, @stephenfin!
